# Generated by Django 5.2.5 on 2026-08-29 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orderstatushistory_changed_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('flat_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('heavy_item_surcharge', models.DecimalField(decimal_places=2, default=0.0, help_text='Additional surcharge applied if cart contains any bulky/heavy items', max_digits=10)),
                ('estimated_delivery', models.CharField(default='1-3 business days', max_length=100)),
                ('is_pickup', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order_index', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order_index', 'flat_fee'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_quote_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='is_heavy_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.deliveryzone'),
        ),
    ]
