# Generated by Django 6.0.6 on 2026-07-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_voucher_is_active_alter_voucher_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, default='🏷️', max_length=50),
        ),
    ]
