# Generated by Django 6.0.6 on 2026-07-12 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_category_icon'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='idx_prod_custom_fields_gin',
        ),
        migrations.RemoveField(
            model_name='product',
            name='custom_fields',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.DeleteModel(
            name='ProductType',
        ),
    ]
