# Generated by Django 5.2.5 on 2026-08-29 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_product_discount_price_product_flash_sale_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_heavy_item',
            field=models.BooleanField(default=False, help_text='Flag for bulky/heavy goods requiring special freight/surcharge'),
        ),
        migrations.CreateModel(
            name='CategoryAttributeSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema', models.JSONField(default=dict, help_text="Mapping of attribute keys to rules: e.g. {'material': {'type': 'string', 'required': false}}")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_schema', to='catalog.category')),
            ],
        ),
        migrations.CreateModel(
            name='PriceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_quantity', models.PositiveIntegerField(help_text='Minimum quantity to activate this bulk unit price')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Discounted price per unit for this volume tier', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_tiers', to='catalog.product')),
            ],
            options={
                'ordering': ['min_quantity'],
                'unique_together': {('product', 'min_quantity')},
            },
        ),
    ]
